name: Release Snapshot to Sonatype

on:
  push:

jobs:
  release_snapshot_sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: sbt
      - name: Release Snapshot to Sonatype
        run: |
          VERSION=$(git describe --tags | cut -f2 -d"@")
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          sbt "clean" "project clientCI" "set isSnapshot := true" "release release-version 0.0.0-2023-01-20-SNAPSHOT with-defaults"
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
