name: 'Publish Release'
on:
  release:
    types: [published]
jobs:
  sbt_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 11
        cache: sbt
    - name: Get version to publish as
      shell: bash
      run: |
        git describe --tags --exact-match HEAD || exit 1
        VERSION=$(git describe --tags | cut -f2 -d"@")
        if [[ ${VERSION:0:1} == "v" ]] ; then
          VERSION=${VERSION:1}
        fi
        echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
    - name: Run sbt release
      shell: bash
      run: |
        echo $PGP_SECRET | base64 --decode | gpg --batch --import
        export GPG_TTY=$(tty)
        RELEASE_TYPE="${{ github.event.release.prerelease && 'snapshot' || 'production' }}"
        echo "Releasing version $VERSION Sonatype as $RELEASE_TYPE"
        sbt -DRELEASE_TYPE=$RELEASE_TYPE "clean" "release cross release-version $VERSION with-defaults"
      env:
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        CAPI_TEST_KEY: ${{ secrets.CAPI_TEST_KEY }}